### ISSUE TITLE
I can’t submit because of Markbot

### ISSUE THREAD

**Issue by Riv67** [Riv67/just-your-type#1]
Hi Christina @muxlowc 

I’m sorry this issue is a little last minute. I thought I was all ready to submit but unfortunately I hadn’t been checking in with Markbot as I was coding and now it’s not very happy with me :/ 
The checks that are failing are listed in the screenshot below. here’s a run-down.

I didn't use grids/units, but my design didn’t need it and I’m happy with the way it looks. I used font-size and line-height because they solved my design problems and they work well. I especially needed font-size because I designed my type between the zetta and yotta sizes and I wanted to be precise. Markbot also does not allow margin on the body. I know this is usually not used, however, for me it worked the best, even after trying many different push/island combos. The last issue is simply that I can’t keep the important tag (!) in my file. You helped with this, it’s there to bypass the default yotta font size. 

I hope I explained these problems well and rationalized why I used the things I did. I’m hoping you can manually submit my repository, even if it means I loose a few marks for not using grids. Like I said, I’m happy with the website and did my best to code it.

![Uploading Screenshot 2020-03-10 20.04.31.png…]()

**Comment by muxlowc** [comment]
@Riv67 no worries, I will go in and give you your mark manually since I told you you could go ahead and do most of those things (haha). So you can just go ahead and write your rationale

**Comment by Riv67** [comment]
Thanks so much!!
